#!/bin/bash
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
  rm -f /usr/doc/parted
fi
# End automatically added section

#======================================================
#  USB Hardware Removal
#======================================================
uninstallUSBHardware() {

   echo
   echo "Removing rules file from ${RULES_DIR}"
   echo ==================================================================
   rm -fv ${RULES_DIR}/*usbdm.rules
}

#======================================================
#  Eclipse Plugin Removal
#======================================================
# $1 - Eclipse directory
#
uninstallEclipsePlugins() {

   local ECLIPSE_DROPIN_DIR="$1/dropins"

   if [[ ! -d ${ECLIPSE_DROPIN_DIR} ]]; then
      echo "Dropin directory ${ECLIPSE_DROPIN_DIR} Not Found"
      return
   fi

   if [[ -f /usr/lib/libUsbdmJniWrapper.so ]]; then
      echo 
      echo "Removing libUsbdmJniWrapper link"
      echo ======================================================================================
      rm -rfv /usr/lib/libUsbdmJniWrapper.so
   fi

   if [[ -d "${ECLIPSE_DROPIN_DIR}/usbdm" ]]; then
      echo 
      echo "Removing Eclipse CDT plugins from ${ECLIPSE_DROPIN_DIR}"
      echo ==================================================================
      rm -rfv "${ECLIPSE_DROPIN_DIR}/usbdm"
   fi
}

#======================================================
#  Eclipse Removal
#======================================================
uninstallEclipse() {

   echo 
   echo "Checking for Eclipse directories"
   echo ==================================================================
   for ECLIPSE_DIR in "/usr/local/eclipse" "/opt/eclipse" "/usr/lib/eclipse"; do
      echo -n "Looking for Eclipse in ${ECLIPSE_DIR}"
      if [[ -d ${ECLIPSE_DIR} ]]; then
         echo " - Found"
         uninstallEclipsePlugins ${ECLIPSE_DIR}
      else
        echo " - Not Found"
      fi
   done
}

#======================================================
#  Codewarrior Instance Removal
#======================================================
uninstallCodewarriorInstance() {

   local CODEWARRIOR_DIR="$1"
   local CODEWARRIOR_ECLIPSE_DIR="$1/eclipse"

   if [[ ! -d ${CODEWARRIOR_ECLIPSE_DIR} ]]; then
      echo 
      echo "Codewarrior Eclipse directory not found"
      echo ======================================================================================
      return
   fi

   uninstallEclipsePlugins "${CODEWARRIOR_ECLIPSE_DIR}"

   CF_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ColdFire/gdi"
   HCS_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/HC08/gdi"
   ARM_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/ARM/gdi"
   DSC_GDI_DIRECTORY="${CODEWARRIOR_DIR}/MCU/CodeWarrior/CodeWarrior_Plugins/Support/DSC/gdi"
   CW_PLUGIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/plugins"
   CW_DROPIN_DIRECTORY="${CODEWARRIOR_DIR}/eclipse/dropins"
   WIZARD_DIRECTORY="${CODEWARRIOR_DIR}/MCU/lib/wizard_data"
   ECLIPSE_CWIDE="${CODEWARRIOR_DIR}/eclipse/cwide"

   CF_GDI_TARGETS="usbdm-cfv1-gdi.so usbdm-cfvx-gdi.so usbdm-cfv1-gdi-debug.so usbdm-cfvx-gdi-debug.so"
   HCS_GDI_TARGETS="usbdm-hcs08-gdi.so usbdm-rs08-gdi.so usbdm-hcs08-gdi-debug.so usbdm-rs08-gdi-debug.so"
   ARM_GDI_TARGETS="usbdm-arm-gdi.so usbdm-arm-gdi-debug.so"
   DSC_GDI_TARGETS="usbdm-dsc-gdi.so usbdm-dsc-gdi-debug.so"

   echo
   echo "Removing CFV1 & CFVx GDI files from ${CF_GDI_DIRECTORY}"
   echo ==================================================================
   for FILENAME in ${CF_GDI_TARGETS}; do
      DESTINATION="${CF_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing RS08 & HCS08 GDI files from ${HCS_GDI_DIRECTORY}"
   echo ==================================================================
   for FILENAME in ${HCS_GDI_TARGETS}; do
      DESTINATION="${HCS_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Kinetis GDI files from ${ARM_GDI_DIRECTORY}"
   echo ==================================================================
   for FILENAME in ${ARM_GDI_TARGETS}; do
      DESTINATION="${ARM_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing DSC GDI files from ${DSC_GDI_DIRECTORY}"
   echo ==================================================================
   for FILENAME in ${DSC_GDI_TARGETS}; do
      DESTINATION="${DSC_GDI_DIRECTORY}/${FILENAME}"
      rm -vf ${DESTINATION}
   done

   echo
   echo "Removing Codewarrior Project Wizard Files for USBDM"
   echo ==================================================================
   echo "Removinglaunch settings"
   rm -vf ${WIZARD_DIRECTORY}/launch_config/usbdm*

   echo
   echo "Unpatching New Project Wizard"
   CODEWARRIOR_PATCH_NEW_WIZARD="PatchNewWizardPlugin_V10.2.xml"
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.projectwizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*

   echo
   echo "Unpatching Change Project Wizard"
   WIZARD_PATCH_FILE=${USBDM_CW_WIZARD_PATCH_DIR}/${CODEWARRIOR_PATCH_CHANGE_WIZARD}
   WIZARD_BASE_DIR=${CW_PLUGIN_DIRECTORY}/"com.freescale.mcu.changewizard_"  
   ${USBDM_BIN_DIR}/MergeXML ${WIZARD_BASE_DIR}\* plugin.xml

   echo 
   echo "Refreshing Eclipse"
   echo touch ${WIZARD_BASE_DIR}\*
   touch ${WIZARD_BASE_DIR}*
   echo ${ECLIPSE_CWIDE} -clean -initialize
   ${ECLIPSE_CWIDE} -clean -initialize
}

#======================================================
#  Codewarrior Removal
#======================================================
uninstallCodewarrior() {

   echo 
   echo "Checking for Codewarrior directory"
   echo ==================================================================
   for CODEWARRIOR_DIR in "/usr/local/Freescale/CodeWarrior_MCU_10.2" "/opt/Freescale/CodeWarrior_MCU_10.2" ; do
      echo -n "Looking for Codewarrior in ${CODEWARRIOR_DIR}"
      if [[ -d ${CODEWARRIOR_DIR} ]]; then
         echo " - Found"
         uninstallCodewarriorInstance ${CODEWARRIOR_DIR}
      else
         echo " - Not Found"
      fi
   done

}

#================================
# USBDM Version
#
MAJOR=4
MINOR=10
VERSION=${MAJOR}.${MINOR}

# Where to find files (relative to /)
DUMMY_ROOT=""
USBDM_BIN_DIR="${DUMMY_ROOT}/usr/bin"
USBDM_LIB_DIR64="${DUMMY_ROOT}/usr/lib/x86_64-linux-gnu/usbdm"
USBDM_LIB_DIR32="${DUMMY_ROOT}/usr/lib/i386-linux-gnu/usbdm"

BITNESS=`getconf LONG_BIT`
if [[ ${BITNESS} == 32 ]]; then
   USBDM_LIB_DIR=${USBDM_LIB_DIR32}
else
   USBDM_LIB_DIR=${USBDM_LIB_DIR64}
fi 

USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
USBDM_CDT_PLUGINS_DIR="${USBDM_SHARED_DIR}/CDT_Plugins"
USBDM_CW_PLUGINS_DIR="${USBDM_SHARED_DIR}/CW_Plugins"
USBDM_CW_LAUNCH_CONFIG_DIR="${USBDM_SHARED_DIR}/LaunchConfig"
USBDM_CW_WIZARD_PATCH_DIR="${USBDM_SHARED_DIR}/WizardPatches"

# System directories
LIB_DIR="/usr/lib"
BIN_DIR="/usr/bin"
RULES_DIR="/etc/udev/rules.d"

uninstallUSBHardware
uninstallEclipse
uninstallCodewarrior

