#!/bin/bash

# Version Information
MAJOR=4
MINOR=10
MICRO=6
NANO=40
DEBIAN_VERSION=1
VERSION=${MAJOR}.${MINOR}.${MICRO}.${NANO}

SOURCE_DIRECTORY=.

# Check if building on 32-bit or 64-bit
BITNESS=`getconf LONG_BIT`

if [[ (${BITNESS} == "32") ]]; then
   # Where to construct the install tree
   DUMMY_ROOT="../usbdm_${VERSION}-${DEBIAN_VERSION}-i386"
   # Library files
   USBDM_LIB_DIR="${DUMMY_ROOT}/usr/lib/i386-linux-gnu"
   # Binary files
   USBDM_BIN_DIR="${DUMMY_ROOT}/usr/bin/i386-linux-gnu"
else
   # Where to construct the install tree
   DUMMY_ROOT="../usbdm_${VERSION}-${DEBIAN_VERSION}-amd64"
   # Library files
   USBDM_LIB_DIR="${DUMMY_ROOT}/usr/lib/x86_64-linux-gnu"
   # Binary files
   USBDM_BIN_DIR="${DUMMY_ROOT}/usr/bin/x86_64-linux-gnu"
fi
# Shared files
USBDM_SHARED_DIR="${DUMMY_ROOT}/usr/share/usbdm"
# Shared document files
USBDM_SHARED_DOC_DIR="${DUMMY_ROOT}/usr/share/doc/usbdm"
# Control files
USBDM_CONTROL_DIR="${DUMMY_ROOT}/DEBIAN"
# Icon files
PIXMAP_DIR="${DUMMY_ROOT}/usr/share/pixmaps"
# Where to put .desktop files
LINUX_APPLICATIONS_DIR="${DUMMY_ROOT}/usr/share/applications"
# Where to put Man page files
USBDM_MANUAL_DIR="${DUMMY_ROOT}/usr/share/man/man1"

if [[ ! -e ${SOURCE_DIRECTORY} ]]; then
   echo Unable to locate Source directory "${SOURCE_DIRECTORY}"
fi

if [[ -e ${DUMMY_ROOT} ]]; then
   echo rm -R ${DUMMY_ROOT}
   rm -R ${DUMMY_ROOT}
fi

mkdir -p ${PIXMAP_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/Hardware-Chip.png ${PIXMAP_DIR}

mkdir -p ${LINUX_APPLICATIONS_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/*.desktop       ${LINUX_APPLICATIONS_DIR}
chmod  644 ${LINUX_APPLICATIONS_DIR}/*.desktop

mkdir -p ${USBDM_SHARED_DOC_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/changelog.Debian.gz   ${USBDM_SHARED_DOC_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/copyright             ${USBDM_SHARED_DOC_DIR}

mkdir -p ${USBDM_SHARED_DIR}
mkdir -p ${USBDM_SHARED_DIR}/CDT_Plugins
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/CDT_Plugins/plugins"             ${USBDM_SHARED_DIR}/CDT_Plugins
mkdir -p ${USBDM_SHARED_DIR}/CW_Plugins
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/CW_Plugins/plugins"              ${USBDM_SHARED_DIR}/CW_Plugins
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/WizardPatches"                   ${USBDM_SHARED_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/DeviceData"                      ${USBDM_SHARED_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/Stationery"                      ${USBDM_SHARED_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/Examples"                        ${USBDM_SHARED_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/FlashImages"                     ${USBDM_SHARED_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/LaunchConfig"                    ${USBDM_SHARED_DIR}

cp -p "${SOURCE_DIRECTORY}/PackageFiles"/Miscellaneous/error.wav            ${USBDM_SHARED_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/TryProgrammer   ${USBDM_SHARED_DIR}	
chmod -f 755 ${USBDM_SHARED_DIR}/TryProgrammer
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/usbdm.rules     ${USBDM_SHARED_DIR}
cp -p "${SOURCE_DIRECTORY}/PackageFiles"/Scripts/*.tcl                      ${USBDM_SHARED_DIR}

mkdir -p ${USBDM_LIB_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/lib"/*      ${USBDM_LIB_DIR}
rm -f ${USBDM_LIB_DIR}/*-debug*
rm -f ${USBDM_LIB_DIR}/*.so
strip ${USBDM_LIB_DIR}/*
chmod 644  ${USBDM_LIB_DIR}/*

mkdir -p ${USBDM_BIN_DIR}
cp -p -r "${SOURCE_DIRECTORY}/PackageFiles/bin"/*      ${USBDM_BIN_DIR}
rm -f ${USBDM_BIN_DIR}/*-debug*
rm -f ${USBDM_BIN_DIR}/*SocketServer*
rm -f ${USBDM_BIN_DIR}/*PipeServer*
rm -f ${USBDM_BIN_DIR}/CopyFlash
rm -f ${USBDM_BIN_DIR}/*TestImage
rm -f ${USBDM_BIN_DIR}/*Example
strip ${USBDM_BIN_DIR}/*
chmod 755  ${USBDM_BIN_DIR}/*

mkdir -p ${USBDM_MANUAL_DIR}
for MANPAGE_FILE in ManPages/*; do   
   cp -p ${MANPAGE_FILE} ${MANPAGE_FILE}.1
   gzip --best -f ${MANPAGE_FILE}.1
   mv ${MANPAGE_FILE}.1.gz ${USBDM_MANUAL_DIR}
done
chmod 644 ${USBDM_MANUAL_DIR}/* 

mkdir ${USBDM_CONTROL_DIR}
for CONTROL_FILE in postinst prerm; do
   cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/${CONTROL_FILE}        ${USBDM_CONTROL_DIR}
   chmod 755 ${USBDM_CONTROL_DIR}/${CONTROL_FILE} 
done

if [[ (${BITNESS} == "32") ]]; then
   cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/control.i386         ${USBDM_CONTROL_DIR}/control
else
   cp -p "${SOURCE_DIRECTORY}/PackageFiles"/MiscellaneousLinux/DEBIAN/control.amd64        ${USBDM_CONTROL_DIR}/control
fi
chmod 755 ${USBDM_CONTROL_DIR}/control 

find ${DUMMY_ROOT} -type d -exec chmod 755 {} \;
find ${USBDM_LIB_DIR} -type f -executable -exec chmod 755 {} \; -exec strip {} \;
find ${USBDM_LIB_DIR} -type f -name \*.so\* -exec chmod 644 {} \;
find ${DUMMY_ROOT} -type f ! -executable -exec chmod 644 {} \;

fakeroot dpkg-deb --build ${DUMMY_ROOT}

lintian ${DUMMY_ROOT}.deb
 
exit

