#!/bin/bash


# Version Information
MAJOR=4
MINOR=10
MICRO=6
NANO=110
DEBIAN_VERSION=1
VERSION=${MAJOR}.${MINOR}.${MICRO}.${NANO}

BITNESS=`getconf LONG_BIT`

if [[ (${BITNESS} == "32") ]]; then
   # Where to construct the install tree
   PACKAGE_FILE="../usbdm_${VERSION}-${DEBIAN_VERSION}-i386.deb"
else
   # Where to construct the install tree
   PACKAGE_FILE="../usbdm_${VERSION}-${DEBIAN_VERSION}-amd64.deb"
fi

sudo apt-get remove usbdm
sudo dpkg -i ${PACKAGE_FILE} 


